# -*- coding: utf-8 -*-
"""assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IcOVTVl03fM0ZfrH44xxdqBHSo7HpRpr
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats
from scipy import integrate

def f(y,x):
  return x*y*np.exp(3*x*y/2 - 25*x**2/32 - 2*y**2)/np.pi

w=integrate.nquad(f,[[-np.inf,np.inf],[-np.inf,np.inf]])
print(f'E(X,Y)=',w)